#!/usr/bin/env tsx
/**
 * Type Sync Script
 *
 * Generates TypeScript types from API OpenAPI spec and syncs to frontends
 *
 * Steps:
 * 1. Generate OpenAPI spec from Zod schemas (API)
 * 2. Generate TypeScript types from OpenAPI spec
 * 3. Copy types to Dashboard
 * 4. Copy types to Widget
 * 5. Validate checksums
 *
 * Usage: npm run sync-types
 */

import { execSync } from 'child_process';
import { copyFileSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { createHash } from 'crypto';

const ROOT_DIR = resolve(__dirname, '..');
const API_DIR = resolve(ROOT_DIR, 'packages/api');
const DASHBOARD_DIR = resolve(ROOT_DIR, 'packages/dashboard');
const WIDGET_DIR = resolve(ROOT_DIR, 'packages/widget');
const GENERATED_DIR = resolve(ROOT_DIR, '.generated');

console.log('🔄 Syncing API types across packages...\n');

// Ensure .generated directory exists
if (!existsSync(GENERATED_DIR)) {
  mkdirSync(GENERATED_DIR, { recursive: true });
}

// Step 1: Generate OpenAPI spec from Zod schemas
console.log('1️⃣  Generating OpenAPI spec from API Zod schemas...');
try {
  execSync('npm run generate:openapi', {
    cwd: API_DIR,
    stdio: 'inherit',
  });
  console.log('   ✅ OpenAPI spec generated\n');
} catch (error) {
  console.error('   ❌ Failed to generate OpenAPI spec');
  process.exit(1);
}

// Step 2: Generate TypeScript types from OpenAPI
console.log('2️⃣  Generating TypeScript types from OpenAPI spec...');
const openapiPath = resolve(API_DIR, 'openapi.json');
const typesOutput = resolve(GENERATED_DIR, 'api-types.ts');

if (!existsSync(openapiPath)) {
  console.error('   ❌ OpenAPI spec not found at:', openapiPath);
  process.exit(1);
}

try {
  execSync(
    `npx openapi-typescript ${openapiPath} -o ${typesOutput}`,
    { stdio: 'inherit' }
  );
  console.log('   ✅ TypeScript types generated\n');
} catch (error) {
  console.error('   ❌ Failed to generate TypeScript types');
  console.error('   Make sure openapi-typescript is installed: npm install -D openapi-typescript');
  process.exit(1);
}

// Step 3: Add header and helper types to generated file
console.log('3️⃣  Adding header and helper types...');
const generatedTypes = readFileSync(typesOutput, 'utf-8');

const header = `/**
 * 🚨 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the API OpenAPI specification.
 * Any manual changes will be overwritten on the next sync.
 *
 * Source: packages/api/openapi.json
 * Generated: ${new Date().toISOString()}
 *
 * To update this file, run:
 *   npm run sync-types
 *
 * Source of truth: packages/api/src/db/schema/
 */

`;

const helperTypes = `
// ==================== Helper Types ====================

/**
 * Extract response type from an endpoint
 * Usage: type ServiceResponse = ApiResponse<'/api/services', 'get'>
 */
export type ApiResponse<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { responses: { 200: { content: { 'application/json': infer T } } } }
  ? T
  : never;

/**
 * Extract request body type from an endpoint
 * Usage: type CreateServiceRequest = ApiRequestBody<'/api/services', 'post'>
 */
export type ApiRequestBody<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { requestBody: { content: { 'application/json': infer T } } }
  ? T
  : never;

/**
 * Extract path parameters from an endpoint
 * Usage: type ServiceParams = ApiParams<'/api/services/{id}', 'get'>
 */
export type ApiParams<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { parameters: { path: infer T } }
  ? T
  : never;

/**
 * Extract query parameters from an endpoint
 * Usage: type BookingQuery = ApiQuery<'/api/bookings', 'get'>
 */
export type ApiQuery<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { parameters: { query: infer T } }
  ? T
  : never;

// ==================== Convenience Types ====================

// Services
export type Service = components['schemas']['Service'];
export type NewService = components['schemas']['NewService'];
export type ServiceList = ApiResponse<'/api/services/user/{slug}', 'get'>;
export type ServiceResponse = ApiResponse<'/api/services/{id}', 'get'>;

// Bookings
export type Booking = components['schemas']['Booking'];
export type NewBooking = components['schemas']['NewBooking'];
export type BookingList = ApiResponse<'/api/bookings', 'get'>;
export type BookingResponse = ApiResponse<'/api/bookings/{id}', 'get'>;
export type CreateBookingResponse = ApiResponse<'/api/bookings', 'post'>;

// Users
export type User = components['schemas']['User'];

// Health
export type HealthResponse = ApiResponse<'/health', 'get'>;
`;

const typesWithHeader = header + generatedTypes + helperTypes;
writeFileSync(typesOutput, typesWithHeader);
console.log('   ✅ Header and helpers added\n');

// Step 4: Copy to Dashboard
console.log('4️⃣  Copying types to Dashboard...');
const dashboardTypesDir = resolve(DASHBOARD_DIR, 'src/types');
const dashboardTypesPath = resolve(dashboardTypesDir, 'api.ts');

if (!existsSync(dashboardTypesDir)) {
  mkdirSync(dashboardTypesDir, { recursive: true });
}

copyFileSync(typesOutput, dashboardTypesPath);
console.log(`   ✅ Dashboard types updated: ${dashboardTypesPath}\n`);

// Step 5: Copy to Widget
console.log('5️⃣  Copying types to Widget...');
const widgetTypesDir = resolve(WIDGET_DIR, 'src/types');
const widgetTypesPath = resolve(widgetTypesDir, 'api.ts');

if (!existsSync(widgetTypesDir)) {
  mkdirSync(widgetTypesDir, { recursive: true });
}

copyFileSync(typesOutput, widgetTypesPath);
console.log(`   ✅ Widget types updated: ${widgetTypesPath}\n`);

// Step 6: Generate checksum for validation
console.log('6️⃣  Generating checksum...');
const checksum = createHash('md5')
  .update(generatedTypes)
  .digest('hex');

const checksumData = {
  checksum,
  timestamp: new Date().toISOString(),
  files: {
    source: openapiPath,
    generated: typesOutput,
    dashboard: dashboardTypesPath,
    widget: widgetTypesPath,
  },
};

const checksumPath = resolve(GENERATED_DIR, 'checksum.json');
writeFileSync(checksumPath, JSON.stringify(checksumData, null, 2));
console.log(`   ✅ Checksum saved: ${checksum.substring(0, 12)}...\n`);

// Summary
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log('✨ Types synced successfully!');
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
console.log(`📄 OpenAPI Spec: ${openapiPath}`);
console.log(`📦 Generated Types: ${typesOutput}`);
console.log(`🎨 Dashboard: ${dashboardTypesPath}`);
console.log(`🎯 Widget: ${widgetTypesPath}`);
console.log(`✅ Checksum: ${checksum.substring(0, 12)}...`);
console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
console.log('⚠️  Remember to commit the updated type files!');
console.log('   git add packages/*/src/types/api.ts .generated/');
