/**
 * 🚨 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated from the API OpenAPI specification.
 * Any manual changes will be overwritten on the next sync.
 *
 * Source: packages/api/openapi.json
 * Generated: 2025-11-13T08:11:06.117Z
 *
 * To update this file, run:
 *   npm run sync-types
 *
 * Source of truth: packages/api/src/db/schema/
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/login": {
    /** Login with email and password */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Login successful */
        200: {
          content: {
            "application/json": {
              /** @description User entity */
              user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string;
                slug: string;
                stripeAccountId: string | null;
                stripeOnboardingComplete: boolean;
                businessName: string | null;
                businessAddress: string | null;
                businessPhone: string | null;
                businessWebsite: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Invalid credentials */
        401: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/register": {
    /** Register new user */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            slug: string;
          };
        };
      };
      responses: {
        /** @description Registration successful */
        201: {
          content: {
            "application/json": {
              /** @description User entity */
              user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string;
                slug: string;
                stripeAccountId: string | null;
                stripeOnboardingComplete: boolean;
                businessName: string | null;
                businessAddress: string | null;
                businessPhone: string | null;
                businessWebsite: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Invalid request or user already exists */
        400: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/logout": {
    /** Logout current user */
    post: {
      responses: {
        /** @description Logout successful */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/auth/google": {
    /** Google OAuth redirect */
    get: {
      responses: {
        /** @description Redirect to Google OAuth */
        302: {
          content: never;
        };
      };
    };
  };
  "/api/users/me": {
    /** Get current user profile */
    get: {
      responses: {
        /** @description User profile retrieved successfully */
        200: {
          content: {
            "application/json": {
              /** @description User entity */
              user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string;
                slug: string;
                stripeAccountId: string | null;
                stripeOnboardingComplete: boolean;
                businessName: string | null;
                businessAddress: string | null;
                businessPhone: string | null;
                businessWebsite: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    /** Update user profile */
    put: {
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            slug?: string;
            businessName?: string;
            businessAddress?: string;
            businessPhone?: string;
            /** Format: uri */
            businessWebsite?: string;
          };
        };
      };
      responses: {
        /** @description Profile updated successfully */
        200: {
          content: {
            "application/json": {
              /** @description User entity */
              user: {
                /** Format: uuid */
                id: string;
                /** Format: email */
                email: string;
                name: string;
                slug: string;
                stripeAccountId: string | null;
                stripeOnboardingComplete: boolean;
                businessName: string | null;
                businessAddress: string | null;
                businessPhone: string | null;
                businessWebsite: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/users/stripe/onboard": {
    /** Start Stripe onboarding process */
    post: {
      responses: {
        /** @description Onboarding URL generated successfully */
        200: {
          content: {
            "application/json": {
              /** Format: uri */
              url: string;
            };
          };
        };
        /** @description User already onboarded or invalid request */
        400: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/services": {
    /** Get all services for authenticated user */
    get: {
      responses: {
        /** @description Services retrieved successfully */
        200: {
          content: {
            "application/json": {
              services: ({
                  /** Format: uuid */
                  id: string;
                  /** Format: uuid */
                  userId: string;
                  name: string;
                  description: string | null;
                  duration: number;
                  depositAmount: number;
                  /** @enum {string} */
                  depositType: "percentage" | "fixed";
                  depositPercentage: number | null;
                  fullPrice: number | null;
                  isActive: boolean | null;
                  requiresApproval: boolean | null;
                  createdAt: string;
                  updatedAt: string;
                })[];
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    /** Create a new service */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            name: string;
            description?: string;
            duration: number;
            depositAmount: number;
            /** @enum {string} */
            depositType?: "percentage" | "fixed";
            depositPercentage?: number;
            fullPrice?: number;
            isActive?: boolean;
            requiresApproval?: boolean;
          };
        };
      };
      responses: {
        /** @description Service created successfully */
        201: {
          content: {
            "application/json": {
              /** @description Service entity */
              service: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                name: string;
                description: string | null;
                duration: number;
                depositAmount: number;
                /** @enum {string} */
                depositType: "percentage" | "fixed";
                depositPercentage: number | null;
                fullPrice: number | null;
                isActive: boolean | null;
                requiresApproval: boolean | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/services/user/{slug}": {
    /** Get active services by user slug (public) */
    get: {
      parameters: {
        path: {
          /** @description User slug or business name */
          slug: string;
        };
      };
      responses: {
        /** @description Services retrieved successfully */
        200: {
          content: {
            "application/json": {
              services: ({
                  /** Format: uuid */
                  id: string;
                  /** Format: uuid */
                  userId: string;
                  name: string;
                  description: string | null;
                  duration: number;
                  depositAmount: number;
                  /** @enum {string} */
                  depositType: "percentage" | "fixed";
                  depositPercentage: number | null;
                  fullPrice: number | null;
                  isActive: boolean | null;
                  requiresApproval: boolean | null;
                  createdAt: string;
                  updatedAt: string;
                })[];
            };
          };
        };
      };
    };
  };
  "/api/services/{id}": {
    /** Get single service by ID */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Service retrieved successfully */
        200: {
          content: {
            "application/json": {
              /** @description Service entity */
              service: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                name: string;
                description: string | null;
                duration: number;
                depositAmount: number;
                /** @enum {string} */
                depositType: "percentage" | "fixed";
                depositPercentage: number | null;
                fullPrice: number | null;
                isActive: boolean | null;
                requiresApproval: boolean | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Service not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    /** Update a service */
    put: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            name?: string;
            description?: string;
            duration?: number;
            depositAmount?: number;
            /** @enum {string} */
            depositType?: "percentage" | "fixed";
            depositPercentage?: number;
            fullPrice?: number;
            isActive?: boolean;
            requiresApproval?: boolean;
          };
        };
      };
      responses: {
        /** @description Service updated successfully */
        200: {
          content: {
            "application/json": {
              /** @description Service entity */
              service: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                name: string;
                description: string | null;
                duration: number;
                depositAmount: number;
                /** @enum {string} */
                depositType: "percentage" | "fixed";
                depositPercentage: number | null;
                fullPrice: number | null;
                isActive: boolean | null;
                requiresApproval: boolean | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Service not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
    /** Delete a service */
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Service deleted successfully */
        200: {
          content: {
            "application/json": {
              success: boolean;
              message: string;
            };
          };
        };
        /** @description Service not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/bookings": {
    /** Get all bookings for authenticated user */
    get: {
      parameters: {
        query?: {
          status?: string;
          from?: string;
          to?: string;
        };
      };
      responses: {
        /** @description Bookings retrieved successfully */
        200: {
          content: {
            "application/json": {
              bookings: ({
                  /** Format: uuid */
                  id: string;
                  /** Format: uuid */
                  userId: string;
                  /** Format: uuid */
                  serviceId: string;
                  customerName: string;
                  /** Format: email */
                  customerEmail: string;
                  customerPhone: string;
                  customerAddress: string | null;
                  bookingDate: string;
                  duration: number;
                  notes: string | null;
                  depositAmount: number;
                  /** @enum {string} */
                  depositStatus: "pending" | "paid" | "failed" | "refunded";
                  /** @enum {string} */
                  status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
                  stripePaymentIntentId: string | null;
                  stripeClientSecret: string | null;
                  createdAt: string;
                  updatedAt: string;
                })[];
            };
          };
        };
      };
    };
    /** Create a booking (public endpoint for widget) */
    post: {
      requestBody?: {
        content: {
          "application/json": {
            /** Format: uuid */
            serviceId: string;
            customerName: string;
            /** Format: email */
            customerEmail: string;
            customerPhone: string;
            customerAddress?: string;
            bookingDate: string;
            notes?: string;
          };
        };
      };
      responses: {
        /** @description Booking created successfully */
        201: {
          content: {
            "application/json": {
              /** @description Booking entity */
              booking: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: uuid */
                serviceId: string;
                customerName: string;
                /** Format: email */
                customerEmail: string;
                customerPhone: string;
                customerAddress: string | null;
                bookingDate: string;
                duration: number;
                notes: string | null;
                depositAmount: number;
                /** @enum {string} */
                depositStatus: "pending" | "paid" | "failed" | "refunded";
                /** @enum {string} */
                status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
                stripePaymentIntentId: string | null;
                stripeClientSecret: string | null;
                createdAt: string;
                updatedAt: string;
              };
              /** @description Stripe payment intent client secret */
              clientSecret: string;
            };
          };
        };
        /** @description Invalid request */
        400: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/bookings/{id}": {
    /** Get single booking by ID */
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Booking retrieved successfully */
        200: {
          content: {
            "application/json": {
              /** @description Booking entity */
              booking: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: uuid */
                serviceId: string;
                customerName: string;
                /** Format: email */
                customerEmail: string;
                customerPhone: string;
                customerAddress: string | null;
                bookingDate: string;
                duration: number;
                notes: string | null;
                depositAmount: number;
                /** @enum {string} */
                depositStatus: "pending" | "paid" | "failed" | "refunded";
                /** @enum {string} */
                status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
                stripePaymentIntentId: string | null;
                stripeClientSecret: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Booking not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/bookings/{id}/status": {
    /** Update booking status */
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            /** @enum {string} */
            status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
          };
        };
      };
      responses: {
        /** @description Booking status updated successfully */
        200: {
          content: {
            "application/json": {
              /** @description Booking entity */
              booking: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: uuid */
                serviceId: string;
                customerName: string;
                /** Format: email */
                customerEmail: string;
                customerPhone: string;
                customerAddress: string | null;
                bookingDate: string;
                duration: number;
                notes: string | null;
                depositAmount: number;
                /** @enum {string} */
                depositStatus: "pending" | "paid" | "failed" | "refunded";
                /** @enum {string} */
                status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
                stripePaymentIntentId: string | null;
                stripeClientSecret: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Booking not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/api/bookings/{id}/cancel": {
    /** Cancel a booking */
    post: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        /** @description Booking cancelled successfully */
        200: {
          content: {
            "application/json": {
              /** @description Booking entity */
              booking: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                userId: string;
                /** Format: uuid */
                serviceId: string;
                customerName: string;
                /** Format: email */
                customerEmail: string;
                customerPhone: string;
                customerAddress: string | null;
                bookingDate: string;
                duration: number;
                notes: string | null;
                depositAmount: number;
                /** @enum {string} */
                depositStatus: "pending" | "paid" | "failed" | "refunded";
                /** @enum {string} */
                status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
                stripePaymentIntentId: string | null;
                stripeClientSecret: string | null;
                createdAt: string;
                updatedAt: string;
              };
            };
          };
        };
        /** @description Booking not found */
        404: {
          content: {
            "application/json": {
              error: string;
              message?: string;
            };
          };
        };
      };
    };
  };
  "/health": {
    /** Health check endpoint */
    get: {
      responses: {
        /** @description Service is healthy */
        200: {
          content: {
            "application/json": {
              /** @enum {string} */
              status: "healthy";
              timestamp: string;
              services: {
                database: {
                  /** @enum {string} */
                  status: "up" | "down";
                  responseTime?: number;
                  error?: string;
                };
                redis: {
                  /** @enum {string} */
                  status: "up" | "down";
                  responseTime?: number;
                  error?: string;
                };
                rabbitmq: {
                  /** @enum {string} */
                  status: "up" | "down";
                  responseTime?: number;
                  error?: string;
                };
              };
            };
          };
        };
        /** @description Service is unhealthy */
        503: {
          content: {
            "application/json": {
              /** @enum {string} */
              status: "unhealthy";
              timestamp: string;
              services?: unknown;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Booking entity */
    Booking: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      userId: string;
      /** Format: uuid */
      serviceId: string;
      customerName: string;
      /** Format: email */
      customerEmail: string;
      customerPhone: string;
      customerAddress: string | null;
      bookingDate: string;
      duration: number;
      notes: string | null;
      depositAmount: number;
      /** @enum {string} */
      depositStatus: "pending" | "paid" | "failed" | "refunded";
      /** @enum {string} */
      status: "pending" | "confirmed" | "cancelled" | "completed" | "refunded";
      stripePaymentIntentId: string | null;
      stripeClientSecret: string | null;
      createdAt: string;
      updatedAt: string;
    };
    /** @description Booking creation payload */
    NewBooking: {
      /** Format: uuid */
      serviceId: string;
      customerName: string;
      /** Format: email */
      customerEmail: string;
      customerPhone: string;
      customerAddress?: string;
      bookingDate: string;
      notes?: string;
    };
    /** @description Service entity */
    Service: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      userId: string;
      name: string;
      description: string | null;
      duration: number;
      depositAmount: number;
      /** @enum {string} */
      depositType: "percentage" | "fixed";
      depositPercentage: number | null;
      fullPrice: number | null;
      isActive: boolean | null;
      requiresApproval: boolean | null;
      createdAt: string;
      updatedAt: string;
    };
    /** @description Service creation payload */
    NewService: {
      name: string;
      description?: string;
      duration: number;
      depositAmount: number;
      /** @enum {string} */
      depositType?: "percentage" | "fixed";
      depositPercentage?: number;
      fullPrice?: number;
      isActive?: boolean;
      requiresApproval?: boolean;
    };
    /** @description User entity */
    User: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name: string;
      slug: string;
      stripeAccountId: string | null;
      stripeOnboardingComplete: boolean;
      businessName: string | null;
      businessAddress: string | null;
      businessPhone: string | null;
      businessWebsite: string | null;
      createdAt: string;
      updatedAt: string;
    };
    /** @description Error response */
    Error: {
      error: string;
      message?: string;
    };
  };
  responses: never;
  parameters: {
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;

// ==================== Helper Types ====================

/**
 * Extract response type from an endpoint
 * Usage: type ServiceResponse = ApiResponse<'/api/services', 'get'>
 */
export type ApiResponse<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { responses: { 200: { content: { 'application/json': infer T } } } }
  ? T
  : paths[Path][Method] extends { responses: { 201: { content: { 'application/json': infer U } } } }
  ? U
  : never;

/**
 * Extract request body type from an endpoint
 * Usage: type CreateServiceRequest = ApiRequestBody<'/api/services', 'post'>
 */
export type ApiRequestBody<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { requestBody: { content: { 'application/json': infer T } } }
  ? T
  : never;

/**
 * Extract path parameters from an endpoint
 * Usage: type ServiceParams = ApiParams<'/api/services/{id}', 'get'>
 */
export type ApiParams<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { parameters: { path: infer T } }
  ? T
  : never;

/**
 * Extract query parameters from an endpoint
 * Usage: type BookingQuery = ApiQuery<'/api/bookings', 'get'>
 */
export type ApiQuery<
  Path extends keyof paths,
  Method extends keyof paths[Path]
> = paths[Path][Method] extends { parameters: { query: infer T } }
  ? T
  : never;

// ==================== Convenience Types ====================

// Services
export type Service = components['schemas']['Service'];
export type NewService = components['schemas']['NewService'];
export type ServiceList = ApiResponse<'/api/services/user/{slug}', 'get'>;
export type ServiceListResponse = ServiceList;
export type ServiceResponse = ApiResponse<'/api/services/{id}', 'get'>;

// Bookings
export type Booking = components['schemas']['Booking'];
export type NewBooking = components['schemas']['NewBooking'];
export type BookingList = ApiResponse<'/api/bookings', 'get'>;
export type BookingListResponse = BookingList;
export type BookingResponse = ApiResponse<'/api/bookings/{id}', 'get'>;
export type CreateBookingResponse = ApiResponse<'/api/bookings', 'post'>;
export type BookingStatus = Booking['status'];

// Users
export type User = components['schemas']['User'];

// Health
export type HealthResponse = ApiResponse<'/health', 'get'>;
